version: 2.1

jobs:
  build:
    docker:
        - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: npm run lint

  test:
    docker:
        - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: npm run tes
  
  analyze:
    docker:
        - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: npm run audit

workflows:
  myworkflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]

